services:
  pulse_app:
    container_name: pulse_app
    build:
      context: .
      dockerfile: Dockerfile  
    volumes:
      - ./logs:/var/log/nginx
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - pulse_network

networks:
  pulse_network:
    driver: bridge