name: Docker Image CI

on:
    push:

jobs:
    build_and_publish_docker:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Get Commit Short Sha
              id: vars
              run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

            - name: Log in to Github Docker Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build Docker Image
              run: |
                docker build . -t ghcr.io/${{ github.repository_owner }}/pulse-app:${{ steps.vars.outputs.SHORT_SHA }} -f Dockerfile 

            - name: Push Docker Image
              run: |
                docker push ghcr.io/${{ github.repository_owner }}/pulse-app:${{ steps.vars.outputs.SHORT_SHA }}
                docker push ghcr.io/${{ github.repository_owner }}/pulse-app:latest
            