name: Docker Image CI

on:
  push:

jobs:
  build_and_publish_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:latest

      - name: Get Commit Short Sha
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Github Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_GHCR_PAT }}

      - name: Build and Push App Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./pulse-app
          file: ./pulse-app/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ secrets.DOCKER_GHCR_USER }}/pulse-app:${{ steps.vars.outputs.SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push and Push Docker Image (Latest Tag)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v4
        with:
          context: ./pulse-app
          file: ./pulse-app/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ secrets.DOCKER_GHCR_USER }}/pulse-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

